spring:
  application:
    name: orderly

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded

server:
  port: 8000
  servlet:
    context-path: /api

security:
  jwt:
    secret-key:
    expiration-time:

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
